services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    depends_on:
      db:
        condition: service_started

  db:
    image: mysql:9.7.0
    restart: always
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
